version: '3'
services:
  db:
    image: mysql:5.7.37
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    volumes:
      - ./sessions:/sessions
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=admin123
    links:
      - db
    depends_on:
      - db